### ISSUE TITLE
crontab possible?

### ISSUE THREAD

**Issue by lightx** [kmi/node-red-contrib-noble#1]
Would it be possible to receive an inject node so that it can run every x second?

**Comment by cpedrinaci** [comment]
I don't think it would be hard to do. Probably the best option is to create another embedded node with an input so that external nodes can trigger the scanning.

One question though would be the duration of the scan. 
Would you want this configurable within that node or would you rather prefer to allow externally switching the scanning off?

**Comment by lightx** [comment]
Great!

Within that node would be best and maybe having it setup so that if it receives msg.timeout it would set to that time?

**Comment by mblackstock** [comment]
I suggest adding an input to the node that turns scanning on or off based on a message.  For example

```
msg.scan = true
```

Would turn on scanning

```
msg.scan = false
```

Turns it off.

**Comment by cpedrinaci** [comment]
Implemented in the last commit based on Mike's code.
In the next release you will be able to send `msg.payload.scan = true` or false to switch the scan on or off.
